name: EnderaOpenChat
version: ${version}
main: org.endera.enderaopenchat.EnderaOpenChat
description: Simple and stable chat plugin
authors: [TurboVadim, Sculmix]
website: https://bisquit.host
api-version: '1.18'
folia-supported: true
depend:
  - EnderaLib
softdepend:
  - DiscordSRV
  - PlaceholderAPI
  - CMI
commands:
  enderachat:
    description: "Base command"
    usage: "/enderachat reload"
    aliases:
      - echat
  msg:
    description: "Send personal message"
    usage: "/msg <arg>"
    aliases:
      - m
      - w
      - whisper
      - tell
permissions:
  echat.msg:
    description: "Send personal messages"
    default: true
  echat.reload:
    description: "Reload the plugin configuration"
    default: op
