name: EnderaOpenChat
version: ${version}
main: org.endera.enderaopenchat.EnderaOpenChat
description: Simple and stable chat plugin
authors: [TurboVadim, Sculmix]
website: https://bisquit.host
api-version: '1.18'
folia-supported: true
depend:
  - EnderaLib
softdepend:
  - DiscordSRV
  - PlaceholderAPI
commands:
  enderachat:
    description: "Base command"
    usage: "/enderachat <arg>"
    aliases:
      - echat
  msg:
    description: "Send personal message"
    usage: "/msg <arg>"
    aliases:
      - m
      - w
      - whisper
      - tell