name: EnderaOpenChat
version: ${projectVersion}
main: org.endera.enderaopenchat.EnderaOpenChat
description: Обычный плагин на чат, разработанный абобиками из Endera
authors: [TurboVadim, Sculmix]
website: https://bisquit.host
api-version: '1.18'
depend:
  - EnderaLib
  - PlaceholderAPI
  - LuckPerms
softdepend:
  - DiscordSRV
commands:
  enderachat:
    description: "Базовая команда"
    usage: "/enderachat <arg>"
  msg:
    description: "Отправить личное сообщение"
    usage: "/msg <arg>"
    aliases:
      - m
      - w
      - whisper
      - tell